import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextProps {
  language: string;
  t: (key: string, args?: Record<string, string | number>) => string;
  setLanguage: (lang: string) => void;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

interface LanguageProviderProps {
  children: React.ReactNode;
}

const translations = {
  en: {
    common: {
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      edit: "Edit",
      delete: "Delete",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      home: "Home",
      submit: "Submit",
      goodMorning: "Good morning",
      goodAfternoon: "Good afternoon",
      goodEvening: "Good evening",
      toGoal: "to goal",
      progressToGoal: "progress to goal",
      complete: "complete",
      distance: "Distance",
      calories: "Calories",
      time: "Time",
      weeklyActivity: "Weekly Activity",
      selectActivity: "Select an activity to start tracking",
      stepsProgress: "Steps Progress",
      goalAchieved: "Goal achieved!",
      stayHydrated: "Stay hydrated!",
      streak: "Streak",
      days: "days",
      average: "Average",
      progress: "Progress",
      target: "Target",
      recent: "Recent",
      trend: "Trend",
      vsLastWeek: "vs last week",
      optimalBedtime: "Optimal Bedtime",
      basedOnBestNights: "based on best nights",
      improving: "Improving",
      declining: "Declining",
      stable: "Stable",
      good: "Good",
      normal: "Normal",
      kcal: "kcal",
      km: "km",
      min: "min",
      ml: "ml",
      kg: "kg",
      cm: "cm",
      bmi: "BMI",
      dayNames: {
        mon: "Mon",
        tue: "Tue", 
        wed: "Wed",
        thu: "Thu",
        fri: "Fri",
        sat: "Sat",
        sun: "Sun"
      }
    },
    dashboard: {
      welcome: "Welcome back!",
      hello: "Hello",
      overview: "Overview",
      activity: "Activity",
      water: "Water",
      sleep: "Sleep",
      weight: "Weight",
      steps: "Steps",
      signOut: "Sign Out",
      dailyGoal: "Daily Goal",
      todaysActivity: "Today's Activity",
      calories: "Calories",
      liters: "L",
      hours: "h",
      current: "Current",
      goal: "Goal",
      trackWeight: "Track Weight",
      todaysTips: "Today's Tips",
    },
    activity: {
      noActivities: "No activities tracked yet.",
      addActivity: "Add Activity",
      editActivity: "Edit Activity",
      deleteActivity: "Delete Activity",
      confirmDelete: "Are you sure you want to delete this activity?",
      activityName: "Activity Name",
      duration: "Duration (minutes)",
      date: "Date",
      notes: "Notes",
      caloriesBurned: "Calories Burned",
      add: "Add",
      update: "Update",
      details: "Details",
      nameRequired: "Activity name is required",
      durationRequired: "Duration is required",
      dateRequired: "Date is required",
      caloriesRequired: "Calories burned is required",
      caloriesInvalid: "Calories burned must be a number",
      durationInvalid: "Duration must be a number",
      edit: "Edit",
      delete: "Delete",
      today: "Today",
      yesterday: "Yesterday",
      thisWeek: "This Week",
      lastWeek: "Last Week",
      thisMonth: "This Month",
      lastMonth: "Last Month",
      allTime: "All Time",
      timeSpent: "Time Spent",
      caloriesBurnedTotal: "Calories Burned (Total)",
      noActivitiesForDate: "No activities for this date",
      description: "Track your fitness activities and monitor your progress",
      todaysProgress: "Today's Progress",
      startWorkout: "Start Workout",
      recentActivity: "Recent Activity",
      quickStart: "Quick Start",
      walking: "Walking",
      running: "Running",
      cycling: "Cycling",
      hiking: "Hiking",
      swimming: "Swimming",
      gym: "Gym",
      startTracking: "Start Tracking",
      stopTracking: "Stop Tracking",
      goal: "Daily Step Goal",
      stepsToday: "Steps Today",
      distance: "Distance Covered",
      time: "Active Time",
    },
    water: {
      trackHydration: "Track your hydration",
      currentIntake: "Current Intake",
      dailyGoal: "Daily Goal",
      addWater: "Add Water",
      waterReminder: "Water Reminder",
      setReminder: "Set Reminder",
      stopReminder: "Stop Reminder",
      reminderDescription: "Set regular reminders to drink water throughout the day",
      reminderInterval: "Reminder Interval (minutes)",
      reminderMinimum: "Minimum 15 minutes",
      reminderMinInterval: "Reminder interval must be at least 15 minutes",
      reminderError: "Reminder Error",
      reminderSet: "Reminder Set",
      reminderSetDescription: "You will receive a reminder every {minutes} minutes",
      reminderActive: "Reminder Active",
      noReminder: "No Reminder Set",
      quickSelect: "Quick Select",
      minutes: "min",
      reminders: "Reminders",
      todaysLog: "Today's Log",
      noWaterLogged: "No water consumption logged yet",
      weeklyOverview: "Weekly Overview",
      reminderNotificationTitle: "Time to drink water! 💧",
      reminderNotificationBody: "Don't forget to hydrate throughout the day",
      customAmount: "Custom Amount",
      addCustomAmount: "Add Custom Amount",
      enterAmountDescription: "Enter the amount of water you want to add",
      amount: "Amount"
    },
    sleep: {
      trackSleep: "Track your sleep",
      addSleepEntry: "Add Sleep Entry",
      editSleepEntry: "Edit Sleep Entry",
      deleteSleepEntry: "Delete Sleep Entry",
      confirmDelete: "Are you sure you want to delete this sleep entry?",
      sleepTime: "Sleep Time",
      wakeUpTime: "Wake Up Time",
      wakeTime: "Wake Up Time",
      date: "Date",
      notes: "Notes",
      add: "Add",
      update: "Update",
      details: "Details",
      sleepTimeRequired: "Sleep time is required",
      wakeUpTimeRequired: "Wake up time is required",
      dateRequired: "Date is required",
      edit: "Edit",
      delete: "Delete",
      totalSleepDuration: "Total Sleep Duration",
      averageSleepDuration: "Average Sleep Duration",
      noSleepData: "No sleep data available",
      bedtime: "Bedtime",
      wakeUp: "Wake Up",
      hours: "hours",
      minutes: "minutes",
      total: "Total",
      quality: "Quality",
      overall: "Overall",
      restless: "Restless",
      interrupted: "Interrupted",
      sound: "Sound",
      light: "Light",
      comfortable: "Comfortable",
      rating: "Rating",
      rateYourSleep: "Rate Your Sleep",
      veryPoor: "Very Poor",
      poor: "Poor",
      average: "Average",
      good: "Good",
      excellent: "Excellent",
      sleepQuality: "Sleep Quality",
      sleepDuration: "Sleep Duration",
      weeklyOverview: "Weekly Overview",
      description: "Monitor your sleep patterns and improve your rest quality",
      lastNightSleep: "Last Night's Sleep",
      duration: "Duration",
      logTonightSleep: "Log Tonight's Sleep",
      statistics: "Statistics",
      averageDuration: "Average Duration",
      averageQuality: "Average Quality",
      totalEntries: "Total Entries",
      bestSleepDay: "Best Sleep Day",
      hrs: "hrs",
      na: "N/A",
      saveSleepData: "Save Sleep Data",
      sleepGoal: "Sleep Goal",
      sleepInsights: "Sleep Insights",
      sleepConsistency: "Sleep Consistency",
      recentTrend: "Recent Trend",
      optimalBedtime: "Optimal Bedtime",
      target: "Target",
      progress: "Progress",
    },
    weight: {
      trackWeight: "Track your weight",
      addWeightEntry: "Add Weight Entry",
      editWeightEntry: "Edit Weight Entry",
      deleteWeightEntry: "Delete Weight Entry",
      confirmDelete: "Are you sure you want to delete this weight entry?",
      weight: "Weight (kg)",
      date: "Date",
      notes: "Notes",
      add: "Add",
      update: "Update",
      details: "Details",
      weightRequired: "Weight is required",
      dateRequired: "Date is required",
      weightInvalid: "Weight must be a number",
      edit: "Edit",
      delete: "Delete",
      weightProgress: "Weight Progress",
      currentWeight: "Current Weight",
      startingWeight: "Starting Weight",
      goalWeight: "Goal Weight",
      noWeightData: "No weight data available",
      weeklyOverview: "Weekly Overview",
      kilograms: "Kilograms",
      weightGoal: "Weight Goal",
      setGoal: "Set Goal",
      startTracking: "Start Tracking",
      current: "Current",
      start: "Start",
      goal: "Goal",
      noGoalSet: "No goal set",
      description: "Monitor your weight progress and achieve your goals",
      left: "left to goal",
      progressChart: "Progress Chart",
      weightHistory: "Weight History",
      enterWeight: "Enter your weight",
      invalidWeight: "Invalid weight",
      enterValidNumber: "Please enter a valid number",
      weightAdded: "Weight added successfully",
      added: "Added",
      toRecords: "to your records",
      noChange: "No change",
      noWeightEntries: "No weight entries recorded yet",
      progress: "Progress",
      progressToGoal: "Progress to Goal",
      weeklyChange: "Weekly Change",
      remaining: "Remaining",
      clickToEdit: "Click to edit",
      targetWeight: "Target Weight",
      quickSelect: "Quick Select",
      insights: "Weight Insights",
      weeklyTrend: "Weekly Trend",
      trendIncreasing: "Weight increasing",
      trendDecreasing: "Weight decreasing", 
      trendStable: "Weight stable",
      consistency: "Consistency",
      goalPrediction: "Goal Prediction",
      goodProgress: "Good progress towards goal",
      slowProgress: "Slow progress, consider adjusting habits",
      offTrack: "Off track, review your plan",
    },
    steps: {
      trackSteps: "Track your steps",
      stepsTaken: "Steps Taken",
      dailyGoal: "Daily Goal",
      setGoal: "Set Goal",
      stepsProgress: "Steps Progress",
      steps: "Steps",
      noStepsData: "No steps data available",
      weeklyOverview: "Weekly Overview",
      congratulations: "Congratulations!",
      goalReached: "You've reached your daily goal!",
      keepGoing: "Keep going!",
    },
    statistics: {
      title: "Statistics",
      description: "Comprehensive overview of your health and fitness data",
      week: "Week",
      month: "Month",
      year: "Year",
      totalActivities: "Total Activities",
      waterIntake: "Water Intake",
      thisWeek: "This Week",
      avgSleep: "Avg Sleep",
      perNight: "per night",
      weightChange: "Weight Change",
      total: "Total",
      allTime: "All Time",
      weeklyActivityTrends: "Weekly Activity Trends",
      stepsAndCalories: "Steps and Calories",
      activityDistribution: "Activity Distribution",
      favoriteActivities: "Your Favorite Activities",
      waterIntakeTrends: "Water Intake Trends",
      dailyWaterConsumption: "Daily Water Consumption",
      sleepPatterns: "Sleep Patterns",
      sleepDurationQuality: "Sleep Duration & Quality",
      weightProgress: "Weight Progress",
      weightJourney: "Your Weight Journey",
      qualityScale: "Quality (1-10)",
      walking: "Walking",
      running: "Running",
      cycling: "Cycling",
      swimming: "Swimming",
      weeklyActivitySteps: "Weekly Steps Progress",
      progress: "Progress",
      healthScore: "Health Score",
      overallHealthMetric: "Overall health assessment based on your activities",
      basedOnActivity: "Based on activity, sleep, hydration and weight data",
      trendAnalysis: "Trend Analysis",
      weeklyComparison: "Current week vs previous week",
      comparison: "Comparison",
      vsAverage: "You vs Average User",
      yourData: "Your Data",
      average: "Average",
      achievements: "Achievements",
      of: "of",
      earned: "earned",
      recentAchievements: "Recent Achievements",
      inProgress: "In Progress",
      hydrationHero: "Hydration Hero",
      sleepChampion: "Sleep Champion",
      goalAchiever: "Goal Achiever",
      stepMaster: "Step Master",
      improving: "Improving",
      declining: "Declining",
      stable: "Stable",
    },
    settings: {
      language: "Language",
      theme: "Theme",
      signOut: "Sign Out",
      deleteAccount: "Delete Account",
      confirmDeleteAccount: "Are you sure you want to delete your account? This action cannot be undone.",
      deleteMyAccount: "Delete My Account",
      settings: "Settings",
      light: "Light",
      dark: "Dark",
      system: "System",
      contactDeveloper: "Contact Developer",
    },
    navigation: {
      home: "Home",
      activity: "Activity",
      water: "Water",
      sleep: "Sleep",
      weight: "Weight",
      statistics: "Statistics",
    },
    auth: {
      signUp: "Sign Up",
      signIn: "Sign In",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      name: "Name",
      signUpMessage: "Don't have an account? Sign up here.",
      signInMessage: "Already have an account? Sign in here.",
      emailRequired: "Email is required",
      passwordRequired: "Password is required",
      nameRequired: "Name is required",
      passwordMinLength: "Password must be at least 6 characters",
      passwordMatch: "Passwords must match",
      invalidEmail: "Invalid email address",
      signOut: "Sign Out",
    },
    feedback: {
      description: "Share your thoughts and suggestions to help us improve the app",
      subject: "Subject",
      message: "Message",
      sent: "Feedback sent successfully",
      error: "Failed to send feedback"
    },
    tips: {
      water: {
        low: "Try to drink {glasses} more glasses of water before dinner",
        good: "Great job on staying hydrated! Keep it up!",
        excellent: "Perfect hydration level! You're doing amazing!",
      },
      steps: {
        start: "Take a 10-minute walk to get your steps going",
        progress: "You're {steps} steps away from your daily goal",
        close: "Almost there! Just {steps} more steps to reach your goal",
        achieved: "Congratulations! You've reached your step goal!",
        exceed: "Amazing! You've exceeded your daily step goal!",
      },
      sleep: {
        short: "Try to get at least 7-8 hours of sleep tonight",
        good: "Great sleep! Try to maintain this schedule",
        long: "You got plenty of sleep! Keep up the good routine",
      },
      weight: {
        track: "Log your weight to track your progress",
        goal: "You're {amount}kg away from your goal weight",
        maintain: "Great job maintaining your target weight!",
      },
      general: {
        consistency: "Consistency is key - track your metrics daily",
        balance: "Remember to balance all aspects of your health",
        celebrate: "Celebrate small wins on your health journey",
        hydrate: "Don't forget to drink water throughout the day",
        move: "Take short breaks to move around every hour",
        rest: "Quality sleep is essential for recovery",
      },
    },
  },
  uk: {
    common: {
      save: "Зберегти",
      cancel: "Скасувати",
      confirm: "Підтвердити",
      edit: "Редагувати",
      delete: "Видалити",
      loading: "Завантаження...",
      error: "Помилка",
      success: "Успіх",
      home: "Головна",
      submit: "Надіслати",
      goodMorning: "Доброго ранку",
      goodAfternoon: "Добрий день",
      goodEvening: "Добрий вечір",
      toGoal: "до цілі",
      progressToGoal: "прогрес до цілі",
      complete: "завершено",
      distance: "Відстань",
      calories: "Калорії",
      time: "Час",
      weeklyActivity: "Тижнева активність",
      selectActivity: "Виберіть активність для початку відстеження",
      stepsProgress: "Прогрес кроків",
      goalAchieved: "Ціль досягнута!",
      stayHydrated: "Залишайтеся зволоженими!",
      streak: "Серія",
      days: "днів",
      average: "Середнє",
      progress: "Прогрес",
      target: "Ціль",
      recent: "Нещодавній",
      trend: "Тренд",
      vsLastWeek: "проти минулого тижня",
      optimalBedtime: "Оптимальний час сну",
      basedOnBestNights: "на основі найкращих ночей",
      improving: "Покращується",
      declining: "Погіршується",
      stable: "Стабільно",
      good: "Добре",
      normal: "Нормально",
      kcal: "ккал",
      km: "км",
      min: "хв",
      ml: "мл",
      kg: "кг",
      cm: "см",
      bmi: "ІМТ",
      dayNames: {
        mon: "Пн",
        tue: "Вт", 
        wed: "Ср",
        thu: "Чт",
        fri: "Пт",
        sat: "Сб",
        sun: "Нд"
      }
    },
    dashboard: {
      welcome: "З поверненням!",
      hello: "Привіт",
      overview: "Огляд",
      activity: "Активність",
      water: "Вода",
      sleep: "Сон",
      weight: "Вага",
      steps: "Кроки",
      signOut: "Вийти",
      dailyGoal: "Денна ціль",
      todaysActivity: "Сьогоднішня активність",
      calories: "Калорії",
      liters: "Л",
      hours: "г",
      current: "Поточна",
      goal: "Ціль",
      trackWeight: "Відстежувати вагу",
      todaysTips: "Поради на сьогодні",
    },
    activity: {
      noActivities: "Поки що немає відстежених активностей.",
      addActivity: "Додати активність",
      editActivity: "Редагувати активність",
      deleteActivity: "Видалити активність",
      confirmDelete: "Ви впевнені, що хочете видалити цю активність?",
      activityName: "Назва активності",
      duration: "Тривалість (хвилини)",
      date: "Дата",
      notes: "Примітки",
      caloriesBurned: "Спалені калорії",
      add: "Додати",
      update: "Оновити",
      details: "Деталі",
      nameRequired: "Назва активності обов'язкова",
      durationRequired: "Тривалість обов'язкова",
      dateRequired: "Дата обов'язкова",
      caloriesRequired: "Кількість спалених калорій обов'язкова",
      caloriesInvalid: "Кількість спалених калорій має бути числом",
      durationInvalid: "Тривалість має бути числом",
      edit: "Редагувати",
      delete: "Видалити",
      today: "Сьогодні",
      yesterday: "Вчора",
      thisWeek: "Цього тижня",
      lastWeek: "Минулого тижня",
      thisMonth: "Цього місяця",
      lastMonth: "Минулого місяця",
      allTime: "За весь час",
      timeSpent: "Витрачений час",
      caloriesBurnedTotal: "Всього спалено калорій",
      noActivitiesForDate: "Немає активностей на цю дату",
      description: "Відстежуйте ваші фітнес-активності та прогрес",
      todaysProgress: "Прогрес сьогодні",
      startWorkout: "Почати тренування",
      recentActivity: "Нещодавня активність",
      quickStart: "Швидкий старт",
      walking: "Ходьба",
      running: "Біг",
      cycling: "Велоспорт",
      hiking: "Походи",
      swimming: "Плавання",
      gym: "Спортзал",
      startTracking: "Почати відстеження",
      stopTracking: "Зупинити відстеження",
      goal: "Денна ціль кроків",
      stepsToday: "Кроків сьогодні",
      distance: "Пройдена відстань",
      time: "Час активності",
    },
    water: {
      trackHydration: "Відстежуйте ваше споживання води",
      currentIntake: "Поточне споживання",
      dailyGoal: "Денна ціль",
      addWater: "Додати воду",
      waterReminder: "Нагадування про воду",
      setReminder: "Встановити нагадування",
      stopReminder: "Зупинити нагадування",
      reminderDescription: "Встановіть регулярні нагадування, щоб пити воду протягом дня",
      reminderInterval: "Інтервал нагадування (хвилини)",
      reminderMinimum: "Мінімум 15 хвилин",
      reminderMinInterval: "Інтервал нагадування повинен бути щонайменше 15 хвилин",
      reminderError: "Помилка нагадування",
      reminderSet: "Нагадування встановлено",
      reminderSetDescription: "Ви отримуватимете нагадування кожні {minutes} хвилин",
      reminderActive: "Нагадування активне",
      noReminder: "Нагадування не встановлено",
      quickSelect: "Швидкий вибір",
      minutes: "хв",
      reminders: "Нагадування",
      todaysLog: "Записи за сьогодні",
      noWaterLogged: "Поки не записано споживання води",
      weeklyOverview: "Огляд за тиждень",
      reminderNotificationTitle: "Час пити воду! 💧",
      reminderNotificationBody: "Не забувайте зволожувати організм протягом дня",
      customAmount: "Власна кількість",
      addCustomAmount: "Додати власну кількість",
      enterAmountDescription: "Введіть кількість води, яку ви хочете додати",
      amount: "Кількість"
    },
    sleep: {
      trackSleep: "Відстежуйте свій сон",
      addSleepEntry: "Додати запис про сон",
      editSleepEntry: "Редагувати запис про сон",
      deleteSleepEntry: "Видалити запис про сон",
      confirmDelete: "Ви впевнені, що хочете видалити цей запис про сон?",
      sleepTime: "Час засинання",
      wakeUpTime: "Час пробудження",
      wakeTime: "Час пробудження",
      date: "Дата",
      notes: "Примітки",
      add: "Додати",
      update: "Оновити",
      details: "Деталі",
      sleepTimeRequired: "Час засинання обов'язковий",
      wakeUpTimeRequired: "Час пробудження обов'язковий",
      dateRequired: "Дата обов'язкова",
      edit: "Редагувати",
      delete: "Видалити",
      totalSleepDuration: "Загальна тривалість сну",
      averageSleepDuration: "Середня тривалість сну",
      noSleepData: "Немає даних про сон",
      bedtime: "Час сну",
      wakeUp: "Пробудження",
      hours: "години",
      minutes: "хвилини",
      total: "Всього",
      quality: "Якість",
      overall: "Загалом",
      restless: "Неспокійний",
      interrupted: "Переривчастий",
      sound: "Звук",
      light: "Світло",
      comfortable: "Зручно",
      rating: "Рейтинг",
      rateYourSleep: "Оцініть свій сон",
      veryPoor: "Дуже погано",
      poor: "Погано",
      average: "Середньо",
      good: "Добре",
      excellent: "Відмінно",
      sleepQuality: "Якість сну",
      sleepDuration: "Тривалість сну",
      weeklyOverview: "Щотижневий огляд",
      description: "Відстежуйте ваші паттерни сну та покращуйте якість відпочинку",
      lastNightSleep: "Сон минулої ночі",
      duration: "Тривалість",
      logTonightSleep: "Записати сьогоднішній сон",
      statistics: "Статистика",
      averageDuration: "Середня тривалість",
      averageQuality: "Середня якість",
      totalEntries: "Всього записів",
      bestSleepDay: "Найкращий день сну",
      hrs: "год",
      na: "N/A",
      saveSleepData: "Зберегти дані про сон",
      sleepGoal: "Ціль сну",
      sleepInsights: "Аналітика сну",
      sleepConsistency: "Послідовність сну",
      recentTrend: "Нещодавній тренд",
      optimalBedtime: "Оптимальний час сну",
      target: "Ціль",
      progress: "Прогрес",
    },
    weight: {
      trackWeight: "Відстежуйте свою вагу",
      addWeightEntry: "Додати запис про вагу",
      editWeightEntry: "Редагувати запис про вагу",
      deleteWeightEntry: "Видалити запис про вагу",
      confirmDelete: "Ви впевнені, що хочете видалити цей запис про вагу?",
      weight: "Вага (кг)",
      date: "Дата",
      notes: "Примітки",
      add: "Додати",
      update: "Оновити",
      details: "Деталі",
      weightRequired: "Вага обов'язкова",
      dateRequired: "Дата обов'язкова",
      weightInvalid: "Вага має бути числом",
      edit: "Редагувати",
      delete: "Видалити",
      weightProgress: "Прогрес ваги",
      currentWeight: "Поточна вага",
      startingWeight: "Початкова вага",
      goalWeight: "Цільова вага",
      noWeightData: "Немає даних про вагу",
      weeklyOverview: "Щотижневий огляд",
      kilograms: "Кілограми",
      weightGoal: "Цільова вага",
      setGoal: "Встановити ціль",
      startTracking: "Почати відстеження",
      current: "Поточна",
      start: "Початок",
      goal: "Ціль",
      noGoalSet: "Ціль не встановлена",
      description: "Відстежуйте прогрес ваги та досягайте цілей",
      left: "до цілі",
      progressChart: "Графік прогресу",
      weightHistory: "Історія ваги",
      enterWeight: "Введіть вашу вагу",
      invalidWeight: "Невірна вага",
      enterValidNumber: "Будь ласка, введіть дійсне число",
      weightAdded: "Вага успішно додана",
      added: "Додано",
      toRecords: "до ваших записів",
      noChange: "Без змін",
      noWeightEntries: "Поки що немає записів про вагу",
      progress: "Прогрес",
      progressToGoal: "Прогрес до цілі",
      weeklyChange: "Щотижнева зміна",
      remaining: "Залишилось",
      clickToEdit: "Клікніть для редагування",
      targetWeight: "Цільова вага",
      quickSelect: "Швидкий вибір",
      insights: "Аналітика ваги",
      weeklyTrend: "Щотижневий тренд",
      trendIncreasing: "Вага зростає",
      trendDecreasing: "Вага зменшується",
      trendStable: "Вага стабільна",
      consistency: "Постійність",
      goalPrediction: "Прогноз цілі",
      goodProgress: "Гарний прогрес до цілі",
      slowProgress: "Повільний прогрес, розгляньте корекцію звичок",
      offTrack: "Поза планом, перегляньте свій план",
    },
    steps: {
      trackSteps: "Відстежуйте свої кроки",
      stepsTaken: "Зроблено кроків",
      dailyGoal: "Денна ціль",
      setGoal: "Встановити ціль",
      stepsProgress: "Прогрес кроків",
      steps: "Кроки",
      noStepsData: "Немає даних про кроки",
      weeklyOverview: "Щотижневий огляд",
      congratulations: "Вітаємо!",
      goalReached: "Ви досягли своєї денної цілі!",
      keepGoing: "Продовжуйте в тому ж дусі!",
    },
    statistics: {
      title: "Статистика",
      description: "Повний огляд ваших даних про здоров'я та фітнес",
      week: "Тиждень",
      month: "Місяць",
      year: "Рік",
      totalActivities: "Всього активностей",
      waterIntake: "Споживання води",
      thisWeek: "Цього тижня",
      avgSleep: "Сер. сон",
      perNight: "за ніч",
      weightChange: "Зміна ваги",
      total: "Всього",
      allTime: "За весь час",
      weeklyActivityTrends: "Тижневі тренди активності",
      stepsAndCalories: "Кроки та калорії",
      activityDistribution: "Розподіл активностей",
      favoriteActivities: "Ваші улюблені активності",
      waterIntakeTrends: "Тренди споживання води",
      dailyWaterConsumption: "Щоденне споживання води",
      sleepPatterns: "Паттерни сну",
      sleepDurationQuality: "Тривалість та якість сну",
      weightProgress: "Прогрес ваги",
      weightJourney: "Ваша подорож ваги",
      qualityScale: "Якість (1-10)",
      walking: "Ходьба",
      running: "Біг",
      cycling: "Велоспорт",
      swimming: "Плавання",
      weeklyActivitySteps: "Щотижневий прогрес кроків",
      progress: "Прогрес",
      healthScore: "Рейтинг здоров'я",
      overallHealthMetric: "Загальна оцінка здоров'я на основі ваших активностей",
      basedOnActivity: "На основі активності, сну, гідратації та даних про вагу",
      trendAnalysis: "Аналіз трендів",
      weeklyComparison: "Поточний тиждень проти минулого тижня",
      comparison: "Порівняння",
      vsAverage: "Ви проти середнього користувача",
      yourData: "Ваші дані",
      average: "Середнє",
      achievements: "Досягнення",
      of: "з",
      earned: "отримано",
      recentAchievements: "Нещодавні досягнення",
      inProgress: "В процесі",
      hydrationHero: "Герой гідратації",
      sleepChampion: "Чемпіон сну",
      goalAchiever: "Досягнувач цілі",
      stepMaster: "Майстер кроків",
      improving: "Покращується",
      declining: "Погіршується",
      stable: "Стабільно",
    },
    settings: {
      language: "Мова",
      theme: "Тема",
      signOut: "Вийти",
      deleteAccount: "Видалити аккаунт",
      confirmDeleteAccount: "Ви впевнені, що хочете видалити свій аккаунт? Цю дію не можна буде скасувати.",
      deleteMyAccount: "Видалити мій аккаунт",
      settings: "Налаштування",
      light: "Світла",
      dark: "Темна",
      system: "Системна",
      contactDeveloper: "Зв'язатися з розробником",
    },
    navigation: {
      home: "Головна",
      activity: "Активність",
      water: "Вода",
      sleep: "Сон",
      weight: "Вага",
      statistics: "Статистика",
    },
    auth: {
      signUp: "Зареєструватися",
      signIn: "Увійти",
      email: "Електронна пошта",
      password: "Пароль",
      confirmPassword: "Підтвердити пароль",
      name: "Ім'я",
      signUpMessage: "Не маєте облікового запису? Зареєструйтеся тут.",
      signInMessage: "Вже маєте обліковий запис? Увійдіть тут.",
      emailRequired: "Електронна пошта обов'язкова",
      passwordRequired: "Пароль обов'язковий",
      nameRequired: "Ім'я обов'язкове",
      passwordMinLength: "Пароль повинен містити не менше 6 символів",
      passwordMatch: "Паролі повинні збігатися",
      invalidEmail: "Недійсна адреса електронної пошти",
      signOut: "Вийти",
    },
    feedback: {
      description: "Поділіться своїми думками та пропозиціями, щоб допомогти нам покращити додаток",
      subject: "Тема",
      message: "Повідомлення",
      sent: "Відгук успішно надіслано",
      error: "Не вдалося надіслати відгук"
    },
    tips: {
      water: {
        low: "Спробуйте випити ще {glasses} склянок води до вечері",
        good: "Чудова робота з підтримкою гідратації! Продовжуйте!",
        excellent: "Ідеальний рівень гідратації! Ви чудово справляєтесь!",
      },
      steps: {
        start: "Прогуляйтеся 10 хвилин, щоб почати набирати кроки",
        progress: "Вам залишилося {steps} кроків до денної цілі",
        close: "Майже готово! Ще лише {steps} кроків до досягнення цілі",
        achieved: "Вітаємо! Ви досягли своєї цілі за кроками!",
        exceed: "Дивовижно! Ви перевищили свою денну ціль за кроками!",
      },
      sleep: {
        short: "Спробуйте спати принаймні 7-8 годин сьогодні вночі",
        good: "Чудовий сон! Спробуйте підтримувати цей розпорядок",
        long: "Ви добре виспалися! Продовжуйте цю гарну рутину",
      },
      weight: {
        track: "Записуйте свою вагу, щоб відстежувати прогрес",
        goal: "Вам залишилося {amount}кг до цільової ваги",
        maintain: "Чудова робота з підтримкою цільової ваги!",
      },
      general: {
        consistency: "Послідовність - це ключ, відстежуйте свої показники щодня",
        balance: "Пам'ятайте про баланс усіх аспектів вашого здоров'я",
        celebrate: "Святкуйте маленькі перемоги у вашій подорожі до здоров'я",
        hydrate: "Не забувайте пити воду протягом дня",
        move: "Робіть короткі перерви для руху кожну годину",
        rest: "Якісний сон важливий для відновлення",
      },
    },
  },
};

const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>(
    typeof window !== 'undefined' ? localStorage.getItem('language') || 'en' : 'en'
  );

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = (key: string, args: Record<string, string | number> = {}) => {
    const keys = key.split('.');
    let translation: any = translations[language as keyof typeof translations];
    
    for (const k of keys) {
      translation = translation?.[k];
    }
    
    if (!translation) {
      console.warn(`Missing translation for key: ${key} in language: ${language}`);
      return key;
    }

    let result = translation;
    for (const argKey in args) {
      result = result.replace(`{${argKey}}`, String(args[argKey]));
    }

    return result;
  };

  const contextValue: LanguageContextProps = {
    language,
    t,
    setLanguage,
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { LanguageProvider, useLanguage };
