import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextProps {
  language: string;
  t: (key: string, args?: Record<string, string | number>) => string;
  setLanguage: (lang: string) => void;
}

const LanguageContext = createContext<LanguageContextProps>({
  language: 'en',
  t: (key: string) => key,
  setLanguage: () => {},
});

interface LanguageProviderProps {
  children: React.ReactNode;
}

const translations = {
  en: {
    common: {
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirm",
      edit: "Edit",
      delete: "Delete",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      home: "Home",
    },
    dashboard: {
      welcome: "Welcome back!",
      overview: "Overview",
      activity: "Activity",
      water: "Water",
      sleep: "Sleep",
      weight: "Weight",
      steps: "Steps",
      signOut: "Sign Out",
    },
    activity: {
      noActivities: "No activities tracked yet.",
      addActivity: "Add Activity",
      editActivity: "Edit Activity",
      deleteActivity: "Delete Activity",
      confirmDelete: "Are you sure you want to delete this activity?",
      activityName: "Activity Name",
      duration: "Duration (minutes)",
      date: "Date",
      notes: "Notes",
      caloriesBurned: "Calories Burned",
      add: "Add",
      update: "Update",
      details: "Details",
      nameRequired: "Activity name is required",
      durationRequired: "Duration is required",
      dateRequired: "Date is required",
      caloriesRequired: "Calories burned is required",
      caloriesInvalid: "Calories burned must be a number",
      durationInvalid: "Duration must be a number",
      edit: "Edit",
      delete: "Delete",
      today: "Today",
      yesterday: "Yesterday",
      thisWeek: "This Week",
      lastWeek: "Last Week",
      thisMonth: "This Month",
      lastMonth: "Last Month",
      allTime: "All Time",
      timeSpent: "Time Spent",
      caloriesBurnedTotal: "Calories Burned (Total)",
      noActivitiesForDate: "No activities for this date",
    },
    water: {
      trackHydration: "Track your hydration",
      currentIntake: "Current Intake",
      dailyGoal: "Daily Goal",
      addWater: "Add Water",
      waterReminder: "Water Reminder",
      setReminder: "Set Reminder",
      stopReminder: "Stop Reminder",
      reminderDescription: "Set regular reminders to drink water throughout the day",
      reminderInterval: "Reminder Interval (minutes)",
      reminderMinimum: "Minimum 15 minutes",
      reminderMinInterval: "Reminder interval must be at least 15 minutes",
      reminderError: "Reminder Error",
      reminderSet: "Reminder Set",
      reminderSetDescription: "You will receive a reminder every {minutes} minutes",
      reminderActive: "Reminder Active",
      noReminder: "No Reminder Set",
      quickSelect: "Quick Select",
      minutes: "min",
      reminders: "Reminders",
      todaysLog: "Today's Log",
      noWaterLogged: "No water consumption logged yet",
      weeklyOverview: "Weekly Overview",
      reminderNotificationTitle: "Time to drink water! 💧",
      reminderNotificationBody: "Don't forget to hydrate throughout the day",
      customAmount: "Custom Amount",
      addCustomAmount: "Add Custom Amount",
      enterAmountDescription: "Enter the amount of water you want to add",
      amount: "Amount"
    },
    sleep: {
      trackSleep: "Track your sleep",
      addSleepEntry: "Add Sleep Entry",
      editSleepEntry: "Edit Sleep Entry",
      deleteSleepEntry: "Delete Sleep Entry",
      confirmDelete: "Are you sure you want to delete this sleep entry?",
      sleepTime: "Sleep Time",
      wakeUpTime: "Wake Up Time",
      date: "Date",
      notes: "Notes",
      add: "Add",
      update: "Update",
      details: "Details",
      sleepTimeRequired: "Sleep time is required",
      wakeUpTimeRequired: "Wake up time is required",
      dateRequired: "Date is required",
      edit: "Edit",
      delete: "Delete",
      totalSleepDuration: "Total Sleep Duration",
      averageSleepDuration: "Average Sleep Duration",
      noSleepData: "No sleep data available",
      bedtime: "Bedtime",
      wakeUp: "Wake Up",
      hours: "hours",
      minutes: "minutes",
      total: "Total",
      quality: "Quality",
      overall: "Overall",
      restless: "Restless",
      interrupted: "Interrupted",
      sound: "Sound",
      light: "Light",
      comfortable: "Comfortable",
      rating: "Rating",
      rateYourSleep: "Rate Your Sleep",
      veryPoor: "Very Poor",
      poor: "Poor",
      average: "Average",
      good: "Good",
      excellent: "Excellent",
      sleepQuality: "Sleep Quality",
      sleepDuration: "Sleep Duration",
      weeklyOverview: "Weekly Overview",
    },
    weight: {
      trackWeight: "Track your weight",
      addWeightEntry: "Add Weight Entry",
      editWeightEntry: "Edit Weight Entry",
      deleteWeightEntry: "Delete Weight Entry",
      confirmDelete: "Are you sure you want to delete this weight entry?",
      weight: "Weight (kg)",
      date: "Date",
      notes: "Notes",
      add: "Add",
      update: "Update",
      details: "Details",
      weightRequired: "Weight is required",
      dateRequired: "Date is required",
      weightInvalid: "Weight must be a number",
      edit: "Edit",
      delete: "Delete",
      weightProgress: "Weight Progress",
      currentWeight: "Current Weight",
      startingWeight: "Starting Weight",
      goalWeight: "Goal Weight",
      noWeightData: "No weight data available",
      weeklyOverview: "Weekly Overview",
      kilograms: "Kilograms",
      weightGoal: "Weight Goal",
      setGoal: "Set Goal",
      startTracking: "Start Tracking",
      current: "Current",
      start: "Start",
      goal: "Goal",
      noGoalSet: "No goal set",
    },
    steps: {
      trackSteps: "Track your steps",
      stepsTaken: "Steps Taken",
      dailyGoal: "Daily Goal",
      setGoal: "Set Goal",
      stepsProgress: "Steps Progress",
      steps: "Steps",
      noStepsData: "No steps data available",
      weeklyOverview: "Weekly Overview",
      congratulations: "Congratulations!",
      goalReached: "You've reached your daily goal!",
      keepGoing: "Keep going!",
    },
    settings: {
      language: "Language",
      theme: "Theme",
      signOut: "Sign Out",
      deleteAccount: "Delete Account",
      confirmDeleteAccount: "Are you sure you want to delete your account? This action cannot be undone.",
      deleteMyAccount: "Delete My Account",
    },
    auth: {
      signUp: "Sign Up",
      signIn: "Sign In",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      name: "Name",
      signUpMessage: "Don't have an account? Sign up here.",
      signInMessage: "Already have an account? Sign in here.",
      emailRequired: "Email is required",
      passwordRequired: "Password is required",
      nameRequired: "Name is required",
      passwordMinLength: "Password must be at least 6 characters",
      passwordMatch: "Passwords must match",
      invalidEmail: "Invalid email address",
      signOut: "Sign Out",
    },
  },
  uk: {
    common: {
      save: "Зберегти",
      cancel: "Скасувати",
      confirm: "Підтвердити",
      edit: "Редагувати",
      delete: "Видалити",
      loading: "Завантаження...",
      error: "Помилка",
      success: "Успіх",
      home: "Головна",
    },
    dashboard: {
      welcome: "З поверненням!",
      overview: "Огляд",
      activity: "Активність",
      water: "Вода",
      sleep: "Сон",
      weight: "Вага",
      steps: "Кроки",
      signOut: "Вийти",
    },
     activity: {
      noActivities: "Поки що немає відстежених активностей.",
      addActivity: "Додати активність",
      editActivity: "Редагувати активність",
      deleteActivity: "Видалити активність",
      confirmDelete: "Ви впевнені, що хочете видалити цю активність?",
      activityName: "Назва активності",
      duration: "Тривалість (хвилини)",
      date: "Дата",
      notes: "Примітки",
      caloriesBurned: "Спалені калорії",
      add: "Додати",
      update: "Оновити",
      details: "Деталі",
      nameRequired: "Назва активності обов'язкова",
      durationRequired: "Тривалість обов'язкова",
      dateRequired: "Дата обов'язкова",
      caloriesRequired: "Кількість спалених калорій обов'язкова",
      caloriesInvalid: "Кількість спалених калорій має бути числом",
      durationInvalid: "Тривалість має бути числом",
      edit: "Редагувати",
      delete: "Видалити",
      today: "Сьогодні",
      yesterday: "Вчора",
      thisWeek: "Цього тижня",
      lastWeek: "Минулого тижня",
      thisMonth: "Цього місяця",
      lastMonth: "Минулого місяця",
      allTime: "За весь час",
      timeSpent: "Витрачений час",
      caloriesBurnedTotal: "Всього спалено калорій",
      noActivitiesForDate: "Немає активностей на цю дату",
    },
    
    // Water tracking translations
    water: {
      trackHydration: "Відстежуйте ваше споживання води",
      currentIntake: "Поточне споживання",
      dailyGoal: "Денна ціль",
      addWater: "Додати воду",
      waterReminder: "Нагадування про воду",
      setReminder: "Встановити нагадування",
      stopReminder: "Зупинити нагадування",
      reminderDescription: "Встановіть регулярні нагадування, щоб пити воду протягом дня",
      reminderInterval: "Інтервал нагадування (хвилини)",
      reminderMinimum: "Мінімум 15 хвилин",
      reminderMinInterval: "Інтервал нагадування повинен бути щонайменше 15 хвилин",
      reminderError: "Помилка нагадування",
      reminderSet: "Нагадування встановлено",
      reminderSetDescription: "Ви отримуватимете нагадування кожні {minutes} хвилин",
      reminderActive: "Нагадування активне",
      noReminder: "Нагадування не встановлено",
      quickSelect: "Швидкий вибір",
      minutes: "хв",
      reminders: "Нагадування",
      todaysLog: "Записи за сьогодні",
      noWaterLogged: "Поки не записано споживання води",
      weeklyOverview: "Огляд за тиждень",
      reminderNotificationTitle: "Час пити воду! 💧",
      reminderNotificationBody: "Не забувайте зволожувати організм протягом дня",
      customAmount: "Власна кількість",
      addCustomAmount: "Додати власну кількість",
      enterAmountDescription: "Введіть кількість води, яку ви хочете додати",
      amount: "Кількість"
    },
    sleep: {
      trackSleep: "Відстежуйте свій сон",
      addSleepEntry: "Додати запис про сон",
      editSleepEntry: "Редагувати запис про сон",
      deleteSleepEntry: "Видалити запис про сон",
      confirmDelete: "Ви впевнені, що хочете видалити цей запис про сон?",
      sleepTime: "Час засинання",
      wakeUpTime: "Час пробудження",
      date: "Дата",
      notes: "Примітки",
      add: "Додати",
      update: "Оновити",
      details: "Деталі",
      sleepTimeRequired: "Час засинання обов'язковий",
      wakeUpTimeRequired: "Час пробудження обов'язковий",
      dateRequired: "Дата обов'язкова",
      edit: "Редагувати",
      delete: "Видалити",
       totalSleepDuration: "Загальна тривалість сну",
      averageSleepDuration: "Середня тривалість сну",
      noSleepData: "Немає даних про сон",
      bedtime: "Час сну",
      wakeUp: "Пробудження",
      hours: "години",
      minutes: "хвилини",
      total: "Всього",
      quality: "Якість",
      overall: "Загалом",
      restless: "Неспокійний",
      interrupted: "Переривчастий",
      sound: "Звук",
      light: "Світло",
      comfortable: "Зручно",
      rating: "Рейтинг",
      rateYourSleep: "Оцініть свій сон",
      veryPoor: "Дуже погано",
      poor: "Погано",
      average: "Середньо",
      good: "Добре",
      excellent: "Відмінно",
      sleepQuality: "Якість сну",
      sleepDuration: "Тривалість сну",
      weeklyOverview: "Щотижневий огляд",
    },
    weight: {
      trackWeight: "Відстежуйте свою вагу",
      addWeightEntry: "Додати запис про вагу",
      editWeightEntry: "Редагувати запис про вагу",
      deleteWeightEntry: "Видалити запис про вагу",
      confirmDelete: "Ви впевнені, що хочете видалити цей запис про вагу?",
      weight: "Вага (кг)",
      date: "Дата",
      notes: "Примітки",
      add: "Додати",
      update: "Оновити",
      details: "Деталі",
      weightRequired: "Вага обов'язкова",
      dateRequired: "Дата обов'язкова",
      weightInvalid: "Вага має бути числом",
      edit: "Редагувати",
      delete: "Видалити",
      weightProgress: "Прогрес ваги",
      currentWeight: "Поточна вага",
      startingWeight: "Початкова вага",
      goalWeight: "Цільова вага",
      noWeightData: "Немає даних про вагу",
      weeklyOverview: "Щотижневий огляд",
      kilograms: "Кілограми",
      weightGoal: "Цільова вага",
      setGoal: "Встановити ціль",
      startTracking: "Почати відстеження",
      current: "Поточна",
      start: "Початок",
      goal: "Ціль",
      noGoalSet: "Ціль не встановлена",
    },
    steps: {
      trackSteps: "Відстежуйте свої кроки",
      stepsTaken: "Зроблено кроків",
      dailyGoal: "Денна ціль",
      setGoal: "Встановити ціль",
      stepsProgress: "Прогрес кроків",
      steps: "Кроки",
      noStepsData: "Немає даних про кроки",
      weeklyOverview: "Щотижневий огляд",
      congratulations: "Вітаємо!",
      goalReached: "Ви досягли своєї денної цілі!",
      keepGoing: "Продовжуйте в тому ж дусі!",
    },
    settings: {
      language: "Мова",
      theme: "Тема",
      signOut: "Вийти",
      deleteAccount: "Видалити аккаунт",
      confirmDeleteAccount: "Ви впевнені, що хочете видалити свій аккаунт? Цю дію не можна буде скасувати.",
      deleteMyAccount: "Видалити мій аккаунт",
    },
    auth: {
      signUp: "Зареєструватися",
      signIn: "Увійти",
      email: "Електронна пошта",
      password: "Пароль",
      confirmPassword: "Підтвердити пароль",
      name: "Ім'я",
      signUpMessage: "Не маєте облікового запису? Зареєструйтеся тут.",
      signInMessage: "Вже маєте обліковий запис? Увійдіть тут.",
      emailRequired: "Електронна пошта обов'язкова",
      passwordRequired: "Пароль обов'язковий",
      nameRequired: "Ім'я обов'язкове",
      passwordMinLength: "Пароль повинен містити не менше 6 символів",
      passwordMatch: "Паролі повинні збігатися",
      invalidEmail: "Недійсна адреса електронної пошти",
      signOut: "Вийти",
    },
  },
};

const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>(
    typeof window !== 'undefined' ? localStorage.getItem('language') || 'en' : 'en'
  );

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = (key: string, args: Record<string, string | number> = {}) => {
    let translation = translations[language as keyof typeof translations]?.[
      key.split('.')[0] as keyof (typeof translations)['en']
    ]?.[key.split('.')[1] as string] || key;

    for (const argKey in args) {
      translation = translation.replace(`{${argKey}}`, String(args[argKey]));
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  return useContext(LanguageContext);
};

export { LanguageProvider, useLanguage };
